### PR TITLE
WIP: Add support for JHipster project detection

### PR DESCRIPTION
**Pull request by bdemers**
partial-fix: #3

### CODE REVIEW

**Comment by bdemers** [comment]
@mraible I took a quick pass at using the standard Spring props and adding support for an `okta.env` file.

I need to break up the code a little, but I _think_ it can all make it in the "setup" goal, but we can fall back to a separate goal if needed

**Comment by mraible** [comment]
Yo da man @bdemers!

**Comment by mraible** [comment]
@bdemers Is there a flag I need to run the plugin with to spit out an `okta.env` file? Also, where should I configure the plugin to create groups and add the `groups` claim?

**Comment by bdemers** [comment]
@mraible still a little work to do (tests being at the top of the list), shortly followed by breaking up the mojo in to different parts (spring, jhipster, etc)

That said, if you build this branch you can try it out and give me feedback:
```sh
mvn install
```

Then pick a project of your choice to run:
```sh
mvn com.okta:okta-maven-plugin:0.2.1-SNAPSHOT:setup \
  -DapplicationConfigFile=okta.env \
  -DuseOktaPropertyNames=false \
  -DcreateGroupClaim=true
```

Open question for you...
Ideally, we should use the OKTA version of the spring config values:

```diff
-      SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_OIDC_ISSUER_URI
+      SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_OKTA_ISSUER_URI
```

That way Spring Boot picks up its default values for the "okta" provider. I can configure it to use "OIDC" but I wanted to bring it up first.

Whatever you decide we can turn that into something like `com.okta:okta-maven-plugin:setup-jhipster` and remove the need for the extra args.

**Comment by mraible** [comment]
@bdemers I finally made the time to test this. Unfortunately, I get the following error:

```
➜  hipapp git:(master) mvn com.okta:okta-maven-plugin:0.2.1-SNAPSHOT:setup \
  -DapplicationConfigFile=okta.env \
  -DuseOktaPropertyNames=false \
  -DcreateGroupClaim=true
[INFO] Scanning for projects...
[INFO]
[INFO] ---------------------< com.mycompany.myapp:hipapp >---------------------
[INFO] Building Hipapp 0.0.1-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- okta-maven-plugin:0.2.1-SNAPSHOT:setup (default-cli) @ hipapp ---
First name: Matt
Last name: Raible
Email address: matt.raible@okta.com
Company: Okta
Creating new Okta Organization, this may take a minute:
OrgUrl: https://dev-615281.okta.com
Check your email address to verify your account.

Writing Okta SDK config to: /Users/mraible/.okta/okta.yaml

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  22.183 s
[INFO] Finished at: 2020-04-03T15:50:28-06:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.okta:okta-maven-plugin:0.2.1-SNAPSHOT:setup (default-cli) on project hipapp: Execution default-cli of goal com.okta:okta-maven-plugin:0.2.1-SNAPSHOT:setup failed: Unsupported config file type: /Users/mraible/hipapp/okta.env -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
Execution time: 23 s.
```

If I run it with `-e`, I get:

```
[ERROR] Unknown lifecycle phase " ". You must specify a valid lifecycle phase or a goal in the format <plugin-prefix>:<goal> or <plugin-group-id>:<plugin-artifact-id>[:<plugin-version>]:<goal>. Available lifecycle phases are: validate, initialize, generate-sources, process-sources, generate-resources, process-resources, compile, process-classes, generate-test-sources, process-test-sources, generate-test-resources, process-test-resources, test-compile, process-test-classes, test, prepare-package, package, pre-integration-test, integration-test, post-integration-test, verify, install, deploy, pre-clean, clean, post-clean, pre-site, site, post-site, site-deploy. -> [Help 1]
org.apache.maven.lifecycle.LifecyclePhaseNotFoundException: Unknown lifecycle phase " ". You must specify a valid lifecycle phase or a goal in the format <plugin-prefix>:<goal> or <plugin-group-id>:<plugin-artifact-id>[:<plugin-version>]:<goal>. Available lifecycle phases are: validate, initialize, generate-sources, process-sources, generate-resources, process-resources, compile, process-classes, generate-test-sources, process-test-sources, generate-test-resources, process-test-resources, test-compile, process-test-classes, test, prepare-package, package, pre-integration-test, integration-test, post-integration-test, verify, install, deploy, pre-clean, clean, post-clean, pre-site, site, post-site, site-deploy.
    at org.apache.maven.lifecycle.internal.DefaultLifecycleExecutionPlanCalculator.calculateLifecycleMappings (DefaultLifecycleExecutionPlanCalculator.java:248)
```

**Comment by bdemers** [comment]
moved maven bits to different repo

**Pull request closed without merging**
